<?php

/**
 * @file
 * Contains commerce_onepayvn.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_onepayvn_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_onepayvn module.
    case 'help.page.commerce_onepayvn':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide payment method for OnePay.vn') . '</p>';
      return $output;

    default:
  }
}
